server:
  applicationConnectors:
    - type: http
      port: 8080

database:
  driverClass: org.h2.Driver
  user: sa
  password: ""
  url: jdbc:h2:mem:test;MODE=Oracle

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.hbm2ddl.auto: create-drop